#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ecdsa
Version  : 0.15
Release  : 53
URL      : https://files.pythonhosted.org/packages/e3/7c/b508ade1feb47cd79222e06d85e477f5cfc4fb0455ad3c70eb6330fc49aa/ecdsa-0.15.tar.gz
Source0  : https://files.pythonhosted.org/packages/e3/7c/b508ade1feb47cd79222e06d85e477f5cfc4fb0455ad3c70eb6330fc49aa/ecdsa-0.15.tar.gz
Summary  : ECDSA cryptographic signature library (pure python)
Group    : Development/Tools
License  : MIT
Requires: ecdsa-license = %{version}-%{release}
Requires: ecdsa-python = %{version}-%{release}
Requires: ecdsa-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev
BuildRequires : py
BuildRequires : pyOpenSSL
BuildRequires : pytest
BuildRequires : six

%description
# Pure-Python ECDSA
[![build status](https://travis-ci.org/warner/python-ecdsa.png)](http://travis-ci.org/warner/python-ecdsa)
[![Coverage Status](https://coveralls.io/repos/warner/python-ecdsa/badge.svg)](https://coveralls.io/r/warner/python-ecdsa)
[![condition coverage](https://img.shields.io/badge/condition%20coverage-81%25-yellow)](https://travis-ci.org/warner/python-ecdsa/jobs/626479178#L776)
[![Latest Version](https://img.shields.io/pypi/v/ecdsa.svg?style=flat)](https://pypi.python.org/pypi/ecdsa/)

%package license
Summary: license components for the ecdsa package.
Group: Default

%description license
license components for the ecdsa package.


%package python
Summary: python components for the ecdsa package.
Group: Default
Requires: ecdsa-python3 = %{version}-%{release}

%description python
python components for the ecdsa package.


%package python3
Summary: python3 components for the ecdsa package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ecdsa package.


%prep
%setup -q -n ecdsa-0.15
cd %{_builddir}/ecdsa-0.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578152528
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ecdsa
cp %{_builddir}/ecdsa-0.15/LICENSE %{buildroot}/usr/share/package-licenses/ecdsa/a76ad7941d20352544795c378b35864426999206
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ecdsa/a76ad7941d20352544795c378b35864426999206

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
